name: dio_annotation_example 

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.1.0
  dio_annotation:
  test: ^1.5.1

dependency_overrides:
  dio_annotation:
    path: ../
