
# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  dio:
    import: "package:dio_annotation/builder.dart"
    builder_factories: ["dioBuilder"]
    build_extensions: {".dart": [".dio.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]